on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs para atualizar os dados
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: shaienne23
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "shaienne23"
          git config --global user.email "shaienneo@gmail.com"

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

